export const CHANNELS_INDEX = 'CHANNELS_INDEX'
export const CHANNEL_STORE = 'CHANNEL_STORE'
export const CHANNEL_UPDATE = 'CHANNEL_UPDATE'
export const CHANNEL_DESTROY = 'CHANNEL_DESTROY'

// CHANNELS
export const CHANGELOG_INDEX = 'CHANGELOG_INDEX'
